Vagrant::Config.run do |config|
  config.vm.box = "wanton"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
  config.vm.boot_mode = :gui
  config.vm.customize do |vm|
          vm.memory_size = 384
          vm.name = "wanton"
  end
  config.vm.forward_port "http", 80,  9000
end
